### ISSUE TITLE
Testing v2.0

### ISSUE THREAD

**Issue by dianashk** [pelias/acceptance-tests#55]
Here's the plan:

* Add `region` tag to tests/suites that will indicate which regions need to be loaded in order for those tests to pass as expected.

```
{
      "in": {
        "input": "search text"
      },
      "user": "sevko",
      "id": 2,
      "regions": [ "london", "new york", "berlin" ]
      ...
}
```

* Allow user to run tests with an array of loaded regions and all tests where region requirements are met should be executed.
* As before allow running the entire set of tests when planet is loaded and no regions are specified.
* Move tests expected to fail into separate pull requests, where each one documents a bug or shortcoming of our system.
* Move pending tests, currently in light blue, to a separate PR as well. Revisit them to fill in result details and turn them into legitimate tests.
* Once all non-binary state tests have been moved out, update the framework to support `pass`/`fail`/`warning` states. Some warnings could be:
   * found but not in the expected position
   * found with N (N=1,?) field difference
   * ??? other ideas
* Create new branch, `production`, and make the `.travis.yaml` file run all tests against production instance
* Change `.travis.yaml` in `master` branch to create a local vagrant instance with configured regions and run acceptance tests applicable to that region only.

**Comment by orangejulius** [comment]
Here's a roughly ordered list of tasks and progress on them. I'll try to keep it up to date

- [x] remove failing tests and put them in their own PRs for later investigation
- [ ] move expected failure tests to their own PRs for later investigation (in progress)
- [ ] move pending tests to separate PRs
- [ ] see if its possible to keep the .travis.yaml file the same across different branches, but still test in the right environment
- [ ] set up a production branch configured to test against production, make master test against staging
- [ ] Allow user to run tests with an array of loaded regions and all tests where region requirements are met should be executed.
- [ ] support tagging of regions in individual tests
- [ ] work on improvements to the test suite for better clarity/more powerful testing

**Comment by dianashk** [comment]
@julian, we'll need to update the feedback app to stop adding the failed and placeholder tests along with passing ones in the same PR

**Comment by orangejulius** [comment]
Yeah good idea. There's a lot of stuff that I can thin of to do on the feedback app and you probably have more? Is there a list somewhere of all of them?
